<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products_discount.proto

namespace GPBMetadata;

class ProductsDiscount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9020a1770726f64756374735f646973636f756e742e70726f746f1210" .
            "70726f6475637473646973636f756e7422330a0c4170706c795265717565" .
            "737412120a0a70726f647563745f6964180120012809120f0a0775736572" .
            "5f69641802200128092280010a0d4170706c79526573706f6e7365123a0a" .
            "08646973636f756e7418012001280b32282e70726f647563747364697363" .
            "6f756e742e4170706c79526573706f6e73652e446973636f756e741a330a" .
            "08446973636f756e74120f0a0770657263656e7418012001280512160a0e" .
            "76616c75655f696e5f63656e7473180220012803325c0a1050726f647563" .
            "7473446973636f756e7412480a054170706c79121e2e70726f6475637473" .
            "646973636f756e742e4170706c79526571756573741a1f2e70726f647563" .
            "7473646973636f756e742e4170706c79526573706f6e7365620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

