<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products_discount.proto

namespace Productsdiscount;

if (false) {
    /**
     * This class is deprecated. Use Productsdiscount\ApplyResponse\Discount instead.
     * @deprecated
     */
    class ApplyResponse_Discount {}
}
class_exists(ApplyResponse\Discount::class);
@trigger_error('Productsdiscount\ApplyResponse_Discount is deprecated and will be removed in the next major release. Use Productsdiscount\ApplyResponse\Discount instead', E_USER_DEPRECATED);

