<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products_discount.proto

namespace Productsdiscount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>productsdiscount.ApplyResponse</code>
 */
class ApplyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.productsdiscount.ApplyResponse.Discount discount = 1;</code>
     */
    protected $discount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Productsdiscount\ApplyResponse\Discount $discount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProductsDiscount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.productsdiscount.ApplyResponse.Discount discount = 1;</code>
     * @return \Productsdiscount\ApplyResponse\Discount
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Generated from protobuf field <code>.productsdiscount.ApplyResponse.Discount discount = 1;</code>
     * @param \Productsdiscount\ApplyResponse\Discount $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkMessage($var, \Productsdiscount\ApplyResponse_Discount::class);
        $this->discount = $var;

        return $this;
    }

}

