<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products_discount.proto

namespace Productsdiscount\ApplyResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>productsdiscount.ApplyResponse.Discount</code>
 */
class Discount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 percent = 1;</code>
     */
    protected $percent = 0;
    /**
     * Generated from protobuf field <code>int64 value_in_cents = 2;</code>
     */
    protected $value_in_cents = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $percent
     *     @type int|string $value_in_cents
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProductsDiscount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 percent = 1;</code>
     * @return int
     */
    public function getPercent()
    {
        return $this->percent;
    }

    /**
     * Generated from protobuf field <code>int32 percent = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 value_in_cents = 2;</code>
     * @return int|string
     */
    public function getValueInCents()
    {
        return $this->value_in_cents;
    }

    /**
     * Generated from protobuf field <code>int64 value_in_cents = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValueInCents($var)
    {
        GPBUtil::checkInt64($var);
        $this->value_in_cents = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Discount::class, \Productsdiscount\ApplyResponse_Discount::class);

